# Generated by Django 4.2.7 on 2023-11-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='board',
            name='label',
            field=models.CharField(max_length=1),
        ),
    ]
