# Generated by Django 4.2.7 on 2023-11-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_board_unique_together_alter_board_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='tag',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
